import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const workSans = Work_Sans({
  weight:["400" , "500"],
  variable: "--font-work-sans"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable}  antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
